version: '3'

services:
  mysql-standalone:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  springboot-mysql:
    image: springboot-mysql:1.0.0
    ports:
      - "8080:8080"
    build:
      context: ./
      args:
        ENVIRONMENT: prod
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone