server:
  port: 5000

spring:
  profiles:
    active: @spring.profiles.active@

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tutorialdb.cvpftolgdbdx.ap-northeast-2.rds.amazonaws.com:3306/tutorialdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE